services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - project-net

  backend1:
    build: .
    container_name: backend-1
    depends_on:
      - db
    environment:
      DATABASE_URL: ${DATABASE_URL}
      BACK_NAME: backend-1
    ports:
      - "8001:8000"

    networks:
      - project-net

  backend2:
    build: .
    container_name: backend-2
    depends_on:
      - db
    environment:
      DATABASE_URL: ${DATABASE_URL}
      BACK_NAME: backend-2
    ports:
      - "8002:8000"

    networks:
      - project-net

  nginx-bot:
    image: nginx:stable
    container_name: nginx-bot
    depends_on:
      - backend1
      - backend2
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - project-net

volumes:
  postgres_data:

networks:
  project-net:
    driver: bridge
