FROM python:3.12-slim

RUN apt-get update && apt-get install -y \
    libpq-dev \
    gcc \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# Copia o entrypoint e dá permissão
COPY entrypoint.sh /app/entrypoint.sh
RUN chmod +x /app/entrypoint.sh

# Muda o diretório de trabalho para /app/app para corrigir os imports
WORKDIR /app/app

# Usa o entrypoint para aplicar migrações antes de iniciar o FastAPI
CMD ["/app/entrypoint.sh"]
